// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PiscAtlas.Models;

#nullable disable

namespace PiscAtlas.Models.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260329182040_AdicionarSistemaUtilizadores")]
    partial class AdicionarSistemaUtilizadores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PiscAtlas.Models.Models.Captura", b =>
                {
                    b.Property<int>("CapturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CapturaId"));

                    b.Property<bool>("AprovadaPeloAdmin")
                        .HasColumnType("bit");

                    b.Property<int>("EspecieId")
                        .HasColumnType("int");

                    b.Property<string>("FotografiaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PescadorNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Peso")
                        .HasColumnType("float");

                    b.Property<int>("PesqueiroId")
                        .HasColumnType("int");

                    b.Property<bool>("PossuiProvasVisuais")
                        .HasColumnType("bit");

                    b.Property<double?>("Tamanho")
                        .HasColumnType("float");

                    b.HasKey("CapturaId");

                    b.HasIndex("EspecieId");

                    b.HasIndex("PesqueiroId");

                    b.ToTable("Capturas");
                });

            modelBuilder.Entity("PiscAtlas.Models.Models.Denuncia", b =>
                {
                    b.Property<int>("DenunciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DenunciaId"));

                    b.Property<int>("CapturaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataDecisao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisaoAdmin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DenuncianteEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DenunciaId");

                    b.HasIndex("CapturaId");

                    b.ToTable("Denuncias");
                });

            modelBuilder.Entity("PiscAtlas.Models.Models.Especie", b =>
                {
                    b.Property<int>("EspecieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspecieId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Habitat")
                        .HasColumnType("int");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCientifico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PesoRecordPt")
                        .HasColumnType("float");

                    b.Property<double?>("TamanhoRecordPt")
                        .HasColumnType("float");

                    b.HasKey("EspecieId");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("PiscAtlas.Models.Models.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventoId"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EspecieAlvoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PesoMinimo")
                        .HasColumnType("float");

                    b.Property<decimal>("PrecoInscricao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("TamanhoMinimo")
                        .HasColumnType("float");

                    b.HasKey("EventoId");

                    b.HasIndex("EspecieAlvoId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("PiscAtlas.Models.Models.Inscricao", b =>
                {
                    b.Property<int>("InscricaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InscricaoId"));

                    b.Property<int>("EstadoPagamento")
                        .HasColumnType("int");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<int?>("MelhorCapturaId")
                        .HasColumnType("int");

                    b.Property<string>("PescadorEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PescadorNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Pontuacao")
                        .HasColumnType("float");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InscricaoId");

                    b.HasIndex("EventoId");

                    b.ToTable("Inscricoes");
                });

            modelBuilder.Entity("PiscAtlas.Models.Models.Pesqueiro", b =>
                {
                    b.Property<int>("PesqueiroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PesqueiroId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotografiaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("PesqueiroId");

                    b.ToTable("Pesqueiros");
                });

            modelBuilder.Entity("PiscAtlas.Models.Models.Captura", b =>
                {
                    b.HasOne("PiscAtlas.Models.Models.Especie", "Especie")
                        .WithMany("Capturas")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PiscAtlas.Models.Models.Pesqueiro", "Pesqueiro")
                        .WithMany("Capturas")
                        .HasForeignKey("PesqueiroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Pesqueiro");
                });

            modelBuilder.Entity("PiscAtlas.Models.Models.Denuncia", b =>
                {
                    b.HasOne("PiscAtlas.Models.Models.Captura", "Captura")
                        .WithMany("Denuncias")
                        .HasForeignKey("CapturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Captura");
                });

            modelBuilder.Entity("PiscAtlas.Models.Models.Evento", b =>
                {
                    b.HasOne("PiscAtlas.Models.Models.Especie", "EspecieAlvo")
                        .WithMany()
                        .HasForeignKey("EspecieAlvoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EspecieAlvo");
                });

            modelBuilder.Entity("PiscAtlas.Models.Models.Inscricao", b =>
                {
                    b.HasOne("PiscAtlas.Models.Models.Evento", "Evento")
                        .WithMany("Inscricoes")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("PiscAtlas.Models.Models.Captura", b =>
                {
                    b.Navigation("Denuncias");
                });

            modelBuilder.Entity("PiscAtlas.Models.Models.Especie", b =>
                {
                    b.Navigation("Capturas");
                });

            modelBuilder.Entity("PiscAtlas.Models.Models.Evento", b =>
                {
                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("PiscAtlas.Models.Models.Pesqueiro", b =>
                {
                    b.Navigation("Capturas");
                });
#pragma warning restore 612, 618
        }
    }
}
